### ISSUE TITLE
Missing xml_dump_dir = "text_files" in create_so_data.py

### ISSUE THREAD

**Issue by vaibhavvarshney0** [justinpayan/StackOverflowNER-NS#1]
Hi,
I have been trying to run your code. But it seems some files are missing. I have downloaded the StackoverflowNER dataset. But still I am not able to get file "text_files" used in the python code line 393 (xml_dump_dir = "/Users/juspayan/Downloads/text_files"). Can you please help me out? If possible please upload the splits u have created for the dataset.

**Comment by justinpayan** [comment]
Hi Vaibhav,

Thanks so much for your interest! Apologies for not having the code in working order in the main branch. I have cleaned up the main branch and written a README explaining how to use it. Please let me know if anything still isn't working or is unclear.

And I've included the data itself in the so_data directory now. As mentioned in the README, you can use the scripts in the repo to re-create that data or make any changes to the episode creation pipeline.

Best,
Justin
